### ISSUE TITLE
Issues on Debian

### ISSUE THREAD

**Issue by marteaurouge** [williamsmj/stowsh#22]
Hey!

I have been using stowsh on my old laptop and it worked great (debian 8)

now updating to the latest debian 9.0, i installed coreutils & findutils with apt,
but i still get the "you need the GNU coreutils" error,

is there something i still need to get?

my install was done from the netinstall so a lot of packages are not included by default, halp!

**Comment by mikepqr** [comment]
Thanks for the bug report! Could you paste the output of `realpath --version` and `which strings` on your new system (and if possible on the old working system too!)?

**Comment by mikepqr** [comment]
Pretty sure this is due to the fact that recent Debian-based distributions (including Ubuntu) do not install binutils (and therefore do not have `strings`). I've removed that dependency, so I'm closing this. Please let me know if you're still running into problems
